name: Lottie Flutter
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  analyze:
    name: Flutter analyze
    strategy:
      matrix:
        flutter: ['stable', 'beta']
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.flutter }}
      - run: flutter doctor
      - run: flutter --version
      - run: flutter pub get
        working-directory: example
      - run: flutter analyze
      - run: flutter pub run tool/prepare_submit.dart
      - name: "check for uncommitted changes"
        run: |
          git diff --exit-code --stat -- . ':(exclude)*pubspec.lock' \
          || (echo "##[error] found changed files after build. please run 'dart tool/prepare_submit.dart'" \
                   "and check in all changes" \
              && exit 1)
        shell: bash
  test:
    name: Run all tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        uses: docker://cirrusci/flutter:2.0.6
        with:
          args: sh run_tests.sh
  build_web_version:
    name: Check that the web version compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: flutter config --enable-web
      - run: flutter precache web
      - run: flutter pub get
        working-directory: example
      - run: flutter build web
        working-directory: example
